#!/usr/bin/env bash

function usage() {
cat<<EOF
Usage: $0 <command>

Commands:
    install         Pulls project and installs dependencies
    build           Build into specified directory, accepts project path as arg
    dev             Serve project locally, accepts project path as arg
    deploy          Deploys project to live environment, accepts deploy path as arg
    cleanup         Delete all temporary files
EOF
exit 0
}

function install() {
    echo "Installing hugo/iamschulz"
    git pull --recurse-submodule
    yarn install
    yarn --cwd themes/iamschulz-hugo-theme install 
}

function build() {
    local targetDir=$1
    if [[ "$targetDir" == "" ]]; then
        targetDir="public"
    fi

    yarn --cwd themes/iamschulz-hugo-theme build
    hugo -d $targetDir --cacheDir $HOME/tmp --cleanDestinationDir
    node convert-images.js dir="./$targetDir"
}

function dev() {
    local targetDir=$1
    if [[ "$targetDir" == "" ]]; then
        targetDir="public"
    fi

    yarn --cwd themes/iamschulz-hugo-theme watch &

    node convert-images.js dir="./$targetDir"
    hugo server -d $targetDir
}

function cleanup() {
    rm -rf public
    rm -rf resources
    rm -rf node_modules
    rm -rf themes/iamschulz-hugo-theme/node_modules
    rm -rf $HOME/tmp/iamschulz-hugo
}

function deploy() {
    local targetDir=$1
    if [[ "$targetDir" == "" ]]; then
        targetDir="../html/next/"
    fi

    install
    build public
    echo "Syncing files to prod directory"
    rsync -rc public/ $targetDir
    echo "Syncing done"
    ./updatePushHeaders.sh
    echo "Finished deployment"
}




### Commands ###

subcommand=$1;

if [ -z "$subcommand" ]; then
    usage
fi

shift
case "$subcommand" in
    install)
        install;;
    build)
        build $@;;
    dev)
        dev $@;;
    cleanup)
        cleanup;;
    deploy)
        deploy $@;;
    *)
        usage;;
esac
